const CONFIG = {
  CANVAS_WIDTH: 1600,
  CANVAS_HEIGHT: 850,
  TILE_SIZE: 5,

  TERRAIN_BARREN: 0,
  TERRAIN_FERTILE: 1,

  STARTING_ORGANISMS: 24,
  STARTING_FOOD: 420,

  MAX_FOOD: 680,
  MAX_ORGANISMS: 1400,

  STARTING_ORGANISM_ENERGY: 180,
  CHILD_ORGANISM_ENERGY: 120,
  REPRODUCTION_ENERGY: 260,
  PARENT_ENERGY_AFTER_REPRODUCTION: 140,

  FOOD_ENERGY_VALUE: 80,
  ORGANISM_MAX_AGE: 2400,
  ORGANISM_FOOD_SEARCH_RADIUS: 20,

  FERTILE_FOOD_GROWTH_CHANCE: 0.95,
  BARREN_FOOD_GROWTH_CHANCE: 0.06,
  RANDOM_DIRECTION_CHANGE_CHANCE: 0.06,

  INITIAL_FOOD_FERTILE_CHANCE: 0.85,
  TERRAIN_FERTILITY_CUTOFF: 0.72,

  TICKS_PER_SIM_UPDATE: 12,
  SIM_SPEED_MULTIPLIER: 1,

  ORGANISM_DRAW_SIZE: 7,
  FOOD_DRAW_SIZE: 2
};